trigger:
  - master

name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: dockerImage
  condition: ${{variables.buildImage}}
  jobs:
  - job: dockerBuild
    strategy:
      matrix:
        mongodb:
          imageName: mongo:latest
        api:
          imageName: mireaninja/schedule_api
          buildContext: './'
        refresh_invoker:
          imageName: mireaninja/refresh_invoker
          buildContext: './refresh_invoker'
        proxy:
          imageName: mireaninja/schedule_proxy
          buildContext: './proxy'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: '$(buildContext)/Dockerfile'
        buildContext: '$(buildContext)'
        tags: |
          $(Build.BuildId)
          latest
- stage: UpdateServices
  jobs:
  - deployment: DeployMongo
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image mongo:$(Build.BuildId) mongodb'
                readyTimeout: '20000'
  - deployment: DeployApi
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image mireaninja/schedule_api:$(Build.BuildId) schedule-rtu_api'
                readyTimeout: '20000'
  - deployment: DeployRefreshInvoker
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image mireaninja/refresh_invoker:$(Build.BuildId) schedule-rtu_refresh_invoker'
                readyTimeout: '20000'
  - deployment: DeployProxy
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image mireaninja/schedule_proxy:$(Build.BuildId) schedule-rtu_proxy'
                readyTimeout: '20000'