trigger:
  - master

name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: dockerImage
  condition: ${{variables.buildImage}}
  jobs:
  - job: dockerBuild
    strategy:
      matrix:
        api:
          imageName: rtuitlab/schedule-rtu-api
          buildContext: './'
        refresh_invoker:
          imageName: rtuitlab/schedule-rtu-refresh-invoker
          buildContext: './refresh_invoker'
        proxy:
          imageName: rtuitlab/schedule-rtu-proxy
          buildContext: './proxy'
    steps:
    - task: Docker@2
      inputs:
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: '$(buildContext)/Dockerfile'
        buildContext: '$(buildContext)'
        tags: |
          $(Build.BuildId)
          latest
- stage: UpdateServices
  jobs:
  - deployment: DeployApi
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/schedule-rtu-api:$(Build.BuildId) schedule-rtu_api'
                readyTimeout: '20000'
  - deployment: DeployRefreshInvoker
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/schedule-rtu-refresh-invoker:$(Build.BuildId) schedule-rtu_refresh_invoker'
                readyTimeout: '20000'
  - deployment: DeployProxy
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/schedule-rtu-proxy:$(Build.BuildId) schedule-rtu_proxy'
                readyTimeout: '20000'