version: "3.9"

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    deploy:
      labels:
        - traefik.enable=false
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  backend:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    depends_on:
      - mongodb
    volumes:
      - ./docs:/app/docs # schedule docs
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
        DEBUG: ${DEBUG-false}
        MONGODB_URL: mongodb://mongodb:27017
        ENV: ${ENV-production}
        DOMAIN: ${DOMAIN-schedule.mirea.ninja}

volumes:
  mongodb_data: