version: '3.8'

volumes: 
  mongodb_volume:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    volumes: 
      - mongodb_volume:/data/db
  api:
    privileged: true
    shm_size: 2g
    image: mireaninja/schedule_api
  refresh_invoker:
    image: mireaninja/refresh_invoker
  proxy:
    image: mireaninja/schedule_proxy
