version: "3.9"

services:
  proxy:
    ports:
      - "80:80"
      - "443:443"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-traefik-public-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.services.traefik-traefik-public.loadbalancer.server.port=80

  backend:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: /start-reload.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    labels:
        - traefik.enable=true
        - traefik.http.routers.traefik-backend-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
        - traefik.http.services.traefik-backend.loadbalancer.server.port=5000
        - traefik.http.routers.traefik-backend-http.entrypoints=http
        - traefik.http.routers.traefik-backend-http.middlewares=traefik-https-redirect
        - traefik.http.routers.traefik-backend-https.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
        - traefik.http.routers.traefik-backend-https.entrypoints=https
        - traefik.http.routers.traefik-backend-https.tls=true
        - traefik.http.routers.traefik-backend-https.tls.certresolver=le
        - traefik.http.routers.traefik-backend-https.middlewares=traefik-https-redirect