version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
  api:
    build: ./app
    ports:
    - "5000:5000"
    environment:
    - SECRET_REFRESH_KEY=
    - MONGODB_URL=mongodb://mongodb:27017/

volumes:
  mongodb_volume:
