version: '3.8'

volumes: 
  mongodb_volume:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    volumes: 
      - mongodb_volume:/data/db
  api:
    privileged: true
    shm_size: 2g
    build: ./
    ports:
    - 5000:5000
    environment:
    - API_SECRET=
  refresh_invoker:
    build: ./refresh_invoker
  proxy:
    build: ./proxy
    ports:
    - 5001:5001